# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438_'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['name'], 'verbose_name': '\u0422\u043e\u0432\u0430\u0440\u044b_'},
        ),
    ]
